### ISSUE TITLE
Validator facade conflicts with laravel validator

### ISSUE THREAD

**Issue by Kwaadpepper** [Kaishiyoku/laravel-color-validation#11]
See [Illuminate\Support\Facades\Validator](https://laravel.com/docs/8.x/validation#manually-creating-validators)

So randomly it breaks my requests like:

Method Kaishiyoku\Validation\Color\Validator::validateRequired|string|min does not exist. 

Using laravel 8 last composer updated version.

I am doing `use Illuminate\Support\Facades\Validator;` so it loads your validator instead of laravel validator.

I think you may rename your validator class.

**Comment by Kwaadpepper** [comment]
A hint may be like https://github.com/Propaganistas/Laravel-Phone/blob/master/src/PhoneServiceProvider.php
registering validation rules inside laravel validator instead of overriding it.

**Comment by Kwaadpepper** [comment]
My bad I wrote something wrong, like :

      'links.*' => [
           'label' => 'required|string|min:2'
      ]

But when the error page showed me color validator, it pushed me on the wrong path sorting this out.


So it works out of the box.

Thanks for the package, BTW.

**Comment by Kaishiyoku** [comment]
@Kwaadpepper you"re welcome! Glad that everything works.
