### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by jedlikowski** [Kaishiyoku/laravel-color-validation#12]
Hi, I've seen there is a commit which adds support for Laravel 9, but there is no new version released to packagist with this support added. Would you be able to release a new version with Laravel 9 support?

**Comment by Kaishiyoku** [comment]
Hello, I will release a new version today as soon as possible, thank you for submitting this issue.

**Comment by Kaishiyoku** [comment]
@jedlikowski I just published a new release on Packagist (https://packagist.org/packages/kaishiyoku/laravel-color-validation#2.0.1) which adds support for Laravel 9.

https://github.com/Kaishiyoku/laravel-color-validation/releases/tag/2.0.1
