### ISSUE TITLE
Error when using an unsupported locale

### ISSUE THREAD

**Issue by poutena** [Kaishiyoku/laravel-color-validation#2]
Having both default and fallback locales to one unsupported by the package lead me to errors I didn't manage to work around, even if I created a matching vendor localisation file according to the [documentation on Overriding Package Language Files](https://laravel.com/docs/5.8/localization#overriding-package-language-files) (i.e., on /resources/lang/vendor/laravel-color-validation/ja/validation.php , in my case). I consistently got a "A non-numeric value encountered" error on "…/vendor/kaishiyoku/laravel-color-validation/src/Kaishiyoku/Validation/Color/ServiceProvider.php 32" when attempting to login. Adding a "ja" localisation directly on the package ( /vendor/kaishiyoku/laravel-color-validation/resources/lang/ja ) fixed this issue.

Nothing too serious after the issue has been tracked down, but it would still be nice to see it fixed and I'm not good enough a coder to do it myself. Thanks in advance!

**Comment by Kaishiyoku** [comment]
Hello. I will investigate the issue as soon as possible. I will inform you when I have a fix for that.

Thank you for reporting the issue.

**Comment by poutena** [comment]
My pleasure, it's the least I can do since I can't fix it myself.

**Comment by Kaishiyoku** [comment]
@sakinobashi I've fixed the issue. You should now be able to use any locale you prefer. If you want to translate Japanese for example, you will have to add a `validation.php` locale to the `/ja` sub-folder (see updated readme). You can also publish all existing locales using `php artisan vendor:publish --provider="Kaishiyoku\Validation\Color\ServiceProvider"`.

If you're facing any other issues feel free to open an issue.

The new version is `1.1.1`, please update your `composer.json` accordingly.
