### ISSUE TITLE
array_keys(include_once(…)) on ServiceProvider::register() causing error

### ISSUE THREAD

**Issue by poutena** [Kaishiyoku/laravel-color-validation#3]
Hello again, and sorry for causing you trouble again!

The register() function on ServiceProvider is throwing an error on my project.

```php
public function register()
    {
        $this->app->resolving('validator', function (Factory $factory, $app) {
            $factory->resolver(function ($translator, $data, $rules, $messages) {
                $colorValidationMessages = trans(self::NAMESPACE . '::validation');
                $fallbackValidationMessages = array_map(function ($value) {
                    return self::NAMESPACE . '::' . $value;
                }, array_keys(include_once(__DIR__ . '/../../../../resources/lang/en/validation.php')));
                $messages = array_merge($messages, is_string($colorValidationMessages) ? $fallbackValidationMessages : $colorValidationMessages);
                return new ColorValidator($translator, $data, $rules, $messages);
            });
        });
    }
```

For some reason I don't quite understand, …/en/validation.php ends up being imported on 
```
$colorValidationMessages = trans(self::NAMESPACE . '::validation');
```
… so the ' import_once ' returns an array before that line, but 'true' after it. That causes:
```
$fallbackValidationMessages = array_map(function ($value) {
    return self::NAMESPACE . '::' . $value;
}, array_keys(include_once(__DIR__ . '/../../../../resources/lang/en/validation.php')));
```
…to break, because instead of array_keys(array) we end up with array_keys(bool).

Changing that 'include_once' to 'include' fixes it, but I'm not sure if this issue is caused by some bad programming from my part and/or if it's the best solution, so I'll leave that decision to you.

**Comment by Kaishiyoku** [comment]
Hello,

I will take a look at it on the weekend.

**Comment by Kaishiyoku** [comment]
Hello @sakinobashi,

sorry for the late response.

I'm pretty busy at the moment, so for the time being I changed the code to 'include' until I have more time to investigate the bug further.

The new release is [1.1.2](https://packagist.org/packages/kaishiyoku/laravel-color-validation)

Sincere regards.

**Comment by Kaishiyoku** [comment]
@sakinobashi Is this issue still present for you? I also wanted you to ask if I should add Japanese translations to the package.
