### ISSUE TITLE
Does not fully support CSS colours

### ISSUE THREAD

**Issue by uuf6429** [Kaishiyoku/laravel-color-validation#4]
The readme clearly states that this package supports CSS Colours, however this is not completely true: values like `red`, `transparent` or `AliceBlue` are valid CSS colours that are not supported by this validator.

On the other hand, I noticed that the original package has been updated in the meantime to support them. 🤷

**Comment by Kaishiyoku** [comment]
Hello, thank you. I haven't been really active on this repo the last months.

I will add additional support for these colors as soon as possible.

**Comment by Kaishiyoku** [comment]
The new release is 1.3.0.
